// samples/vue/am4editor-vue-sample/src/components/Settings.vue
<template>
  <div class="settings">
    <h1>General Launcher/Editor settings</h1>
    <p>
      <b>Modify settings used as the basis for all demos.</b>
    </p>
    <p>Note: these are just a few of available settings used here for demo purposes.</p>

    <h2>Launch Editor in...</h2>
    <label>
      <input type="radio" name="target-type" value="inline" 
        :checked="launcherSettings.target.type === 'inline'"
        @change="setTargetType($event.target.value)"
      />
      iframe (inline)
    </label>
    <label>
      <input type="radio" name="target-type" value="window" 
        :checked="launcherSettings.target.type === 'window'"
        @change="setTargetType($event.target.value)"
      />
      window
    </label>

    <h2>Enabled modules</h2>
    <label v-for="item in allModules" :key="item">
      <input type="checkbox" 
        :value="item" 
        :checked="editorConfig.enabledModules.indexOf(item) > -1"
        @change="toggleModule($event.target.value, $event.target.checked)"
      />
      {{ item }}
    </label>

    <h2>Available themes</h2>
    <label v-for="theme in allThemes" :key="`theme-${theme.name}`">
      <input type="checkbox" 
        :value="theme.name" 
        :checked="editorConfig.engineConfig.availableThemes.find(t => t.name === theme.name) !== undefined"
        @change="toggleTheme($event.target.value, $event.target.checked)"
      />
      {{ theme.label }}
    </label>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

// import Editor Launcher
import * as am4editor from '@amcharts/editor4';

@Component
export default class Settings extends Vue {
  @Prop() allModules!: am4editor.ModuleType[];
  @Prop() allThemes!: am4editor.IThemeInfo[];
  @Prop() launcherSettings!: am4editor.ILauncherConfig;
  @Prop() editorConfig!: am4editor.IConfig;

  private toggleModule(name: string, isEnabled: boolean) {
    this.$emit('toggle-module', name, isEnabled);
  }

  private toggleTheme(name: string, isEnabled: boolean) {
    this.$emit('toggle-theme', name, isEnabled);
  }

  private setTargetType(targetType: string) {
    this.$emit('set-target-type', targetType);
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>

// samples/angular/am4editor-angular-sample/src/app/settings/settings.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import * as am4editor from '@amcharts/editor4';

export interface TargetChangedEvent {
    target: string;
}

export interface ModuleToggledEvent {
    name: am4editor.ModuleType;
    isEnabled: boolean;
}

export interface ThemeToggledEvent {
    name: string;
    isEnabled: boolean;
}

@Component({
    selector: 'app-settings',
    templateUrl: './settings.component.html',
    styleUrls: ['./settings.component.css']
})
export class SettingsComponent {
    @Input() allModules: Array<am4editor.ModuleType>;
    @Input() allThemes: Array<am4editor.IThemeInfo>;
    @Input() launcherSettings: am4editor.ILauncherConfig;
    @Input() editorConfig: am4editor.IConfig;

    @Output() onTargetChanged = new EventEmitter<TargetChangedEvent>();
    @Output() onModuleToggled = new EventEmitter<ModuleToggledEvent>();
    @Output() onThemeToggled = new EventEmitter<ThemeToggledEvent>();

    public toggleModule(name: am4editor.ModuleType, isEnabled: boolean) {
        this.onModuleToggled.emit({ name, isEnabled });
    }

    public toggleTheme(name: string, isEnabled: boolean) {
        this.onThemeToggled.emit({ name, isEnabled });
    }

    public setTargetType(target: string) {
        this.onTargetChanged.emit({ target });
    }

    public isModuleChecked(name: am4editor.ModuleType): boolean {
        return this.editorConfig.enabledModules.indexOf(name) > -1;
    }

    public isThemeChecked(theme: string): boolean {
        return this.editorConfig.engineConfig.availableThemes.find(t => t.name === theme) !== undefined;
    }

    public themeKey(theme: am4editor.IThemeInfo): string {
        return `theme-${theme.name}`;
    }
}

<div class="settings">
  <h1>General Launcher/Editor settings</h1>
  <p>
    <b>Modify settings used as the basis for all demos.</b>
  </p>
  <p>Note: these are just a few of available settings used here for demo purposes.</p>

  <h2>Launch Editor in...</h2>
  <label>
    <input type="radio" name="target-type" value="inline"
      [checked]="launcherSettings.target.type === 'inline'"
      (change)="setTargetType($event.target.value)"
    />
    iframe (inline)
  </label>
  <label>
    <input type="radio" name="target-type" value="window"
      [checked]="launcherSettings.target.type === 'window'"
      (change)="setTargetType($event.target.value)"
    />
    window
  </label>

  <h2>Enabled modules</h2>
  <label *ngFor="let item of allModules">
    <input type="checkbox"
      [value]="item"
      [checked]="isModuleChecked(item)"
      (change)="toggleModule($event.target.value, $event.target.checked)"
    />
    {{ item }}
  </label>

  <h2>Available themes</h2>
  <label *ngFor="let theme of allThemes; trackBy: themeKey">
    <input type="checkbox"
      [value]="theme.name"
      [checked]="isThemeChecked(theme.name)"
      (change)="toggleTheme($event.target.value, $event.target.checked)"
    />
    {{ theme.label }}
  </label>
</div>
