// samples/angular/am4editor-angular-sample/src/app/new-chart-from-data/new-chart-from-data.component.ts
import { Component, Input } from '@angular/core';

// import amCharts
import * as am4core from '@amcharts/amcharts4/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as am4charts from '@amcharts/amcharts4/charts';
import '@amcharts/amcharts4/charts'; // "hack" to prevent charts from being optimized-out as unused
// import themes
// eslint-disable-next-line @typescript-eslint/camelcase
import am4themes_animated from '@amcharts/amcharts4/themes/animated';
// eslint-disable-next-line @typescript-eslint/camelcase
import am4themes_dark from '@amcharts/amcharts4/themes/dark';

// import Editor Launcher
import * as am4editor from '@amcharts/editor4';

@Component({
  selector: 'app-new-chart-from-data',
  templateUrl: './new-chart-from-data.component.html',
  styleUrls: ['./new-chart-from-data.component.css']
})
export class NewChartFromDataComponent {
	chart?: am4core.Sprite;
  launcher?: am4editor.EditorLauncher;
  previewBackgroundColor = 'white';

  @Input() launcherSettings: am4editor.ILauncherConfig;
  @Input() editorConfig: am4editor.IConfig;

  launchEditor() {
    this.launcher = new am4editor.EditorLauncher(this.launcherSettings);

    this.launcher.addEventListener('save', this.renderChart);
    this.launcher.addEventListener('close', () => {
      if (this.launcher) {
        this.launcher.close();
      }
    });

    // create a copy of global editor config so we don't modify it
    const editorConfig: am4editor.IConfig = JSON.parse(JSON.stringify(this.editorConfig));
    editorConfig.enabledModules = ['design', 'home'];
    editorConfig.allowDefaultTemplates = true;
    editorConfig.presetData = {
      data: [
        { cat: 'c1', val: 10, val2: 21, },
        { cat: 'c2', val: 20, val2: 10, },
        { cat: 'c3', val: 40, val2: 14, },
        { cat: 'c4', val: 18, val2: 28, }
      ],
      templatePropertyMap: new Map([
        ['category', 'cat'],
        ['value', 'val'],
        ['value1', 'val'],
        ['value2', 'val']
      ])
    };

    this.launcher.editorConfig = editorConfig;

    this.launcher.launch();
  }

  renderChart(event?: am4editor.ILauncherEventArguments) {
    if (event) {
      if (this.launcher) {
        this.launcher.close();
      }

      if (event.appliedThemes) {
        this.applyChartThemes(event.appliedThemes);
      }

      if (this.chart !== undefined) {
        this.chart.dispose();
      }

      this.chart = am4core.createFromConfig(event.chartConfig, "chartdiv-new-from-data");
    }
  }

  applyChartThemes(themes: string[]) {
    am4core.unuseAllThemes();

    // just a sampling of applying a couple of themes
    if (themes) {
      themes.forEach(t => {
        switch (t) {
          case 'am4themes_animated': {
            am4core.useTheme(am4themes_animated);
            break;
          }
          case 'am4themes_dark': {
            am4core.useTheme(am4themes_dark);
            break;
          }
        }
      });
    }

    // get background color from applied themes
    const interfaceColors = new am4core.InterfaceColorSet();
    this.previewBackgroundColor = interfaceColors.getFor('background').hex;
  }

  ngOnDestroy() {
    if (this.chart !== undefined) {
      // cleanup after ourselves
      this.chart.dispose();
    }
  }
}

<div class="new-chart">
  <div class="page-intro">
    <h1>Create a new chart from data</h1>
    <p>
      Create a new chart based on the data we supply.
    </p>
  </div>
  <div class="chartdiv" id="chartdiv-new-from-data" [ngStyle]="{ 'background-color': previewBackgroundColor }">
    <div class="placeholder" (click)="launchEditor()">click here to create a new chart</div>
  </div>
  <div class="comments">
    <h2>Comments</h2>
    <p>In this demo we let users create a new chart based on the preset data we supply</p>
    <ul>
      <li>We override global settings so that only <code>home</code> and <code>design</code> modules are enabled;</li>
      <li>We supply our data via <code>presetData</code> config property;</li>
      <li>We configure the mapping between our data structure and standard template data fields (category, value, value1, value2, etc.)</li>
    </ul>

    <p>Note that our data set may have more or less data/values than some templates expect so it won't fit perfectly in all templates.
      In a real life scenario you would supply your own templates that match the shape of your data set.
    </p>
  </div>
</div>

// samples/vue/am4editor-vue-sample/src/components/NewChartFromData.vue
<template>
  <div class="new-chart">
    <div class="page-intro">
      <h1>Create a new chart from data</h1>
      <p>
        Create a new chart based on the data we supply.
      </p>
    </div>
    <div class="chartdiv" ref="chartdiv" :style="{ backgroundColor: previewBackgroundColor }">
      <div class="placeholder" @click="launchEditor">click here to create a new chart</div>
    </div>
    <div class="comments">
      <h2>Comments</h2>
      <p>In this demo we let users create a new chart based on the preset data we supply</p>
      <ul>
        <li>We override global settings so that only <code>home</code> and <code>design</code> modules are enabled;</li>
        <li>We supply our data via <code>presetData</code> config property;</li>
        <li>We configure the mapping between our data structure and standard template data fields (category, value, value1, value2, etc.)</li>
      </ul>

      <p>Note that our data set may have more or less data/values than some templates expect so it won't fit perfectly in all templates.
        In a real life scenario you would supply your own templates that match the shape of your data set.
      </p>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

// import amCharts
import * as am4core from '@amcharts/amcharts4/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as am4charts from '@amcharts/amcharts4/charts';
import '@amcharts/amcharts4/charts'; // "hack" to prevent charts from being optimized-out as unused
// import themes
// eslint-disable-next-line @typescript-eslint/camelcase
import am4themes_animated from '@amcharts/amcharts4/themes/animated';
// eslint-disable-next-line @typescript-eslint/camelcase
import am4themes_dark from '@amcharts/amcharts4/themes/dark';

// import Editor Launcher
import * as am4editor from '@amcharts/editor4';

@Component
export default class NewChart extends Vue {
  chart?: am4core.Sprite;
  launcher?: am4editor.EditorLauncher;
  previewBackgroundColor = 'white';

  @Prop() launcherSettings!: am4editor.ILauncherConfig;
  @Prop() editorConfig!: am4editor.IConfig;

  launchEditor() {
    this.launcher = new am4editor.EditorLauncher(this.launcherSettings);
    
    this.launcher.addEventListener('save', this.renderChart);
    this.launcher.addEventListener('close', () => { 
      if (this.launcher) {
        this.launcher.close(); 
      }
    });

    // create a copy of global editor config so we don't modify it
    const editorConfig: am4editor.IConfig = JSON.parse(JSON.stringify(this.editorConfig));
    editorConfig.enabledModules = ['design', 'home'];
    editorConfig.allowDefaultTemplates = true;
    editorConfig.presetData = {
      data: [
        { cat: 'c1', val: 10, val2: 21, },
        { cat: 'c2', val: 20, val2: 10, },
        { cat: 'c3', val: 40, val2: 14, },
        { cat: 'c4', val: 18, val2: 28, }
      ],
      templatePropertyMap: new Map([
        ['category', 'cat'],
        ['value', 'val'],
        ['value1', 'val'],
        ['value2', 'val']
      ])
    };

    this.launcher.editorConfig = editorConfig;

    this.launcher.launch();
  }

  renderChart(event?: am4editor.ILauncherEventArguments) {
    if (event) {
      if (this.launcher) {
        this.launcher.close();
      }

      if (event.appliedThemes) {
        this.applyChartThemes(event.appliedThemes);
      }

      if (this.chart !== undefined) {
        this.chart.dispose();
      }

      this.chart = am4core.createFromConfig(event.chartConfig, this.$refs.chartdiv as HTMLElement);
    }
  }

  applyChartThemes(themes: string[]) {
    am4core.unuseAllThemes();

    // just a sampling of applying a couple of themes
    if (themes) {
      themes.forEach(t => {
        switch (t) {
          case 'am4themes_animated': {
            am4core.useTheme(am4themes_animated);
            break;
          }
          case 'am4themes_dark': {
            am4core.useTheme(am4themes_dark);
            break;
          }
        }
      });
    }

    // get background color from applied themes
    const interfaceColors = new am4core.InterfaceColorSet();
    this.previewBackgroundColor = interfaceColors.getFor('background').hex;
  }

  beforeDestroy() {
    if (this.chart !== undefined) {
      // cleanup after ourselves
      this.chart.dispose();
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
