// samples/angular/am4editor-angular-sample/src/app/app.component.ts
import { Component } from '@angular/core';
import { TargetChangedEvent, ModuleToggledEvent, ThemeToggledEvent } from './settings/settings.component';
import * as am4editor from '@amcharts/editor4';

type PageType = 'home' | 'new-chart' | 'edit-chart' | 'new-chart-from-data' | 'edit-chart-type' | 'settings';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    public readonly allModules: Array<am4editor.ModuleType> = ['home', 'design', 'data', 'code'];
    public readonly allThemes: Array<am4editor.IThemeInfo> = [
        {
            name: 'am4themes_animated',
            label: 'Animated'
        },
        {
            name: 'am4themes_dark',
            label: 'Dark'
        }
    ];

    public launcherSettings: am4editor.ILauncherConfig = {
        editorUrl: '/assets/am4editor/',
        target: { type: 'inline' }
    };
    public editorConfig: am4editor.IConfig = {
        enabledModules: ['home', 'design', 'data', 'code'],
        engineConfig: {
            availableThemes: [
                {
                    name: 'am4themes_animated',
                    label: 'Animated'
                },
                {
                    name: 'am4themes_dark',
                    label: 'Dark'
                }
            ]
        }
    };

    public activePage: PageType = 'home';

    public menuSwitch(newPage: PageType) {
        this.activePage = newPage;
    }

    public setTargetType(event: TargetChangedEvent) {
        this.launcherSettings.target.type = event.target === 'window' ? 'window' : 'inline';
    }

    public toggleModule(event: ModuleToggledEvent) {
        const modules = this.editorConfig.enabledModules;
        if (modules) {
            if (!event.isEnabled && modules.indexOf(event.name) > -1) {
                modules.splice(modules.indexOf(event.name), 1);
            } else if ((event.isEnabled && modules.indexOf(event.name) === -1)) {
                modules.push(event.name);
            }
        }
    }

    public toggleTheme(event: ThemeToggledEvent) {
        const themes = this.editorConfig.engineConfig.availableThemes;
        if (themes) {
            if (!event.isEnabled && themes.findIndex(t => t.name === event.name) > -1) {
                themes.splice(themes.findIndex(t => t.name === event.name), 1);
            } else if ((event.isEnabled && themes.findIndex(t => t.name === event.name) === -1)) {
                const theme = this.allThemes.find(t => t.name === event.name)
                if (theme) {
                    themes.push(theme);
                }
            }
        }
    }
}

<div id="app">
  <header>
    <div class="logo" (click)="menuSwitch('home')">
      <a href="#" (click)="menuSwitch('home')">amCharts 4 Editor Demo</a>
    </div>
  </header>

  <nav>
    <ul class="menu menu-primary">
      <li (click)="menuSwitch('new-chart')">
        <div class="menu-item-text"><a href="#" (click)="menuSwitch('new-chart')">New chart</a></div>
      </li>
      <li (click)="menuSwitch">
        <div class="menu-item-text"><a href="#" (click)="menuSwitch('edit-chart')">Edit chart</a></div>
      </li>
      <li (click)="menuSwitch">
        <div class="menu-item-text"><a href="#" (click)="menuSwitch('new-chart-from-data')">New chart from data</a></div>
      </li>
      <li (click)="menuSwitch">
        <div class="menu-item-text"><a href="#" (click)="menuSwitch('edit-chart-type')">Edit chart type</a></div>
      </li>

    </ul>

    <ul class="menu menu-secondary">
      <li (click)="menuSwitch('settings')">
        <div class="menu-item-text">Settings</div>
      </li>
    </ul>
  </nav>

  <main [ngSwitch]="activePage">
    <app-home *ngSwitchCase="'home'"></app-home>
    <app-new-chart *ngSwitchCase="'new-chart'"
      [launcherSettings]="launcherSettings"
      [editorConfig]="editorConfig">
    </app-new-chart>
    <app-edit-chart *ngSwitchCase="'edit-chart'"
      [launcherSettings]="launcherSettings"
      [editorConfig]="editorConfig">
    </app-edit-chart>
    <app-new-chart-from-data *ngSwitchCase="'new-chart-from-data'"
      [launcherSettings]="launcherSettings"
      [editorConfig]="editorConfig">
    </app-new-chart-from-data>
    <app-edit-chart-type *ngSwitchCase="'edit-chart-type'"
      [launcherSettings]="launcherSettings"
      [editorConfig]="editorConfig">
    </app-edit-chart-type>
    <app-settings *ngSwitchCase="'settings'"
      [launcherSettings]="launcherSettings"
      [editorConfig]="editorConfig"
      [allModules]="allModules"
      [allThemes]="allThemes"
      (onTargetChanged)="setTargetType($event)"
      (onModuleToggled)="toggleModule($event)"
      (onThemeToggled)="toggleTheme($event)">
    </app-settings>
  </main>
</div>

// samples/react/am4editor-react-sample/src/App.js
import React, { Component } from 'react';
import './App.css';

import Home from './Home';
import NewChart from './NewChart';
import Settings from './Settings';
import EditChart from './EditChart';
import NewChartFromData from './NewChartFromData';
import EditChartType from './EditChartType';

class App extends Component {
  allModules = ['home', 'design', 'data', 'code'];
  allThemes = [
    {
      name: 'am4themes_animated',
      label: 'Animated'
    },
    {
      name: 'am4themes_dark',
      label: 'Dark'
    }
  ];

 
  constructor(props) {
    super(props);
    this.state = {
      currentPage: 'home',
      launcherSettings: {
        editorUrl: '/am4editor/',
        target: { type: 'inline' }
      },
      editorConfig: {
        enabledModules: ['home', 'design', 'data', 'code'],
        engineConfig: {
          availableThemes: [
            {
              name: 'am4themes_animated',
              label: 'Animated'
            },
            {
              name: 'am4themes_dark',
              label: 'Dark'
            }
          ]
        }
      }
    }

    this.menuSwitch = this.menuSwitch.bind(this);
    this.setTargetType = this.setTargetType.bind(this);
    this.toggleModule = this.toggleModule.bind(this);
    this.toggleTheme = this.toggleTheme.bind(this);
  }

  menuSwitch(page) {
    this.setState( { currentPage: page } );
  }

  setTargetType(target) {
    const newState = Object.assign({}, this.state.launcherSettings);
    newState.target.type = target;

    this.setState( { launcherSettings: newState } );
  }

  toggleModule(name, isEnabled) {
    const newState = Object.assign({}, this.state.editorConfig);
    const modules = newState.enabledModules;
    if (modules) {
      if (!isEnabled && modules.indexOf(name) > -1) {
        modules.splice(modules.indexOf(name), 1);
      } else if ((isEnabled && modules.indexOf(name) === -1)) {
        modules.push(name);
      }
    }
    this.setState( { editorConfig: newState } );
  }

  toggleTheme(name, isEnabled) {
    const newState = Object.assign({}, this.state.editorConfig);
    const themes = newState.engineConfig.availableThemes;
    if (themes) {
      if (!isEnabled && themes.findIndex(t => t.name === name) > -1) {
        themes.splice(themes.findIndex(t => t.name === name), 1);
      } else if ((isEnabled && themes.findIndex(t => t.name === name) === -1)) {
        const theme = this.allThemes.find(t => t.name === name)
        if (theme) {
          themes.push(theme);
        }
      }
    }
    this.setState( { editorConfig: newState } );
  }

  render() {
    return (
      <div className="App">
        <header>
          <div className="logo" onClick={() => this.menuSwitch('home')}>
            <a href="#home" onClick={() => this.menuSwitch('home')}>amCharts 4 Editor Demo</a>
          </div>
        </header>

        <nav>
          <ul className="menu menu-primary">
            <li onClick={() => this.menuSwitch('new-chart')}>
              <div className="menu-item-text">
                <a href="#new-chart" onClick={() => this.menuSwitch('new-chart')}
                  >New chart</a>
              </div>
            </li>
            <li onClick={() => this.menuSwitch('edit-chart')}>
              <div className="menu-item-text">
                <a href="#edit-chart" onClick={() => this.menuSwitch('edit-chart')}
                  >Edit chart</a></div>
            </li>
            <li onClick={() => this.menuSwitch('new-chart-from-data')}>
              <div className="menu-item-text">
                <a href="#new-chart-from-data" onClick={() => this.menuSwitch('new-chart-from-data')}
                >New chart from data</a></div>
            </li>
            <li onClick={() => this.menuSwitch('edit-chart-type')}>
              <div className="menu-item-text">
                <a href="#edit-chart-type" onClick={() => this.menuSwitch('edit-chart-type')}
                  >Edit chart type</a></div>
            </li>

          </ul>

          <ul className="menu menu-secondary">
            <li onClick={() => this.menuSwitch('settings')}>
              <div className="menu-item-text">Settings</div>
            </li>
          </ul>
        </nav>

        <main>
          {this.state.currentPage === 'home' && <Home />}

          {this.state.currentPage === 'new-chart' && 
            <NewChart 
              launcherSettings={this.state.launcherSettings} 
              editorConfig={this.state.editorConfig}
            />
          }
          {this.state.currentPage === 'edit-chart' && 
            <EditChart 
              launcherSettings={this.state.launcherSettings} 
              editorConfig={this.state.editorConfig}
            />
          }
          {this.state.currentPage === 'new-chart-from-data' && 
            <NewChartFromData 
              launcherSettings={this.state.launcherSettings} 
              editorConfig={this.state.editorConfig}
            />
          }
          {this.state.currentPage === 'edit-chart-type' && 
            <EditChartType
              launcherSettings={this.state.launcherSettings} 
              editorConfig={this.state.editorConfig}
            />
          }
          {this.state.currentPage === 'settings' && 
            <Settings 
              launcherSettings={this.state.launcherSettings} 
              editorConfig={this.state.editorConfig}
              allModules={this.allModules} 
              allThemes={this.allThemes} 
              onTargetChanged={this.setTargetType}
              onModuleToggled={this.toggleModule}
              onThemeToggled={this.toggleTheme}
            />
          }
        </main>

      </div>
    );
  }
}

export default App;
